Desktop version
ZewdieMc/Portfolio pull request #5
Opened 2023-01-19 14:15 UTC by ZewdieMc

## Created Desktop version for

- [ ]  `navigation` bar
- [ ] `headline` section
- [ ] `works` sections
- [ ] `about myself` section
- [ ] `contact form` section

2023-01-19 16:04 UTC, amejid requested changes
Hi @ZewdieMc, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
- Correct use of Github flow :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 16:04 UTC, amejid commented on index.html
> +            </ul>
- [x] Good job with the design. There are some small things remaining to achieve perfection. Kindly adjust the left and right spacing on the toolbar to match the Figma design. The spacing you have looks a bit smaller when compared to the design. 🤝️

**Your Design**
![Screenshot from 2023-01-19 17-41-33](https://user-images.githubusercontent.com/17243325/213480277-e9136c05-c929-4198-a8fc-4919a1265570.png)

**Figma Design**
![Screenshot from 2023-01-19 17-41-12](https://user-images.githubusercontent.com/17243325/213480273-6425d9f3-291a-45a8-82bf-1e51e075d10a.png)

2023-01-19 16:04 UTC, amejid commented on index.html
>                  feature or website Look through some of my work and experience!
- [x] Kindly update the `font-weight` on the `I'm Zewdie...` to match the design. ✍️
- [x] Currently, the paragraph `I'm a software...` is overlapping with the background image. I suggest you minimize the width and push down the whole text including the `h1` to prevent overlapping and match the template. 🥸️ Please increase the spacing on the left of the entire text as it looks a bit smaller when compared to the design.

**Your Design**

![Screenshot from 2023-01-19 17-42-47](https://user-images.githubusercontent.com/17243325/213483063-23db52d8-1be6-42c2-9af1-c82a457bba6c.png)

**Figma Design**

![Screenshot from 2023-01-19 17-43-22](https://user-images.githubusercontent.com/17243325/213483095-099ffac9-1282-4e07-a5f0-721cdfd9b4b7.png)

2023-01-19 16:04 UTC, amejid commented on index.html
> +                <button type="button" class="action">See Project</button>
- [x] Please increase the spacing on the sides of the card to match the design. It's currently looking a bit tight. 🧐️
- [x] Kindly update the `font-weight` of the project title, `Tonic` according to the design. 😎️
- [x] I suggest you use the correct background color. i.e(`#F4F5F7`) 🤝️
- [x] Please increase the space between the image and the content to match the template. 🥸️

**Your Design**

![Screenshot from 2023-01-19 17-45-41](https://user-images.githubusercontent.com/17243325/213485452-22baef4e-d835-4e91-bdee-e17e37f6441b.png)

**Figma Design**

![Screenshot from 2023-01-19 17-44-47](https://user-images.githubusercontent.com/17243325/213485530-4bfcd8ae-b1df-41af-a07a-f073bc51681d.png)

2023-01-19 16:04 UTC, amejid commented on index.html
> +            <ul class="links">
- [x] Kindly fix the image paths for your social icons so they can get displayed correctly. I adding a `.` before the path will get the job done. 😎️

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/17243325/213487565-1489225c-34eb-488e-9a3f-68287f5da494.png" width="200">|<img src="https://user-images.githubusercontent.com/17243325/213487572-f83f2c23-1c48-45a8-adfc-22a205f10577.png" width="200">|

2023-01-19 16:04 UTC, amejid commented on index.html
>              <p>Hello I’m a software developer! I can help you build a product , feature or website Look through some of
- [x] Currently the left and the right sides of the about section are taking 50% each, but when looking at the Figma design thoroughly the left side is taking 40% while the right side is taking 60%. Kindly update it accordingly. Since you are using a `grid`, I believe it will be a piece of cake. 😎️
- [x] Kindly update the `font-weight` of the title `About Myself` to match the template. 🙂️
- [x] Please increase the horizontal and vertical spacing around the whole about section to match the Figma design. ✍️
- [x] The images inside the languages `HTML, CSS, Jvascript` are aligned to the left inside their containers, while your images are aligned in the center. Kindly adjust them accordingly.

**Your Design**

![Screenshot from 2023-01-19 17-52-20](https://user-images.githubusercontent.com/17243325/213489939-188b30e4-4fa9-44c5-9c06-dd16bb136fd7.png)

**Figma Design**

![Screenshot from 2023-01-19 17-51-49](https://user-images.githubusercontent.com/17243325/213490055-be71054d-f6f4-40da-bd44-7491ea5903f8.png)

2023-01-19 16:04 UTC, amejid commented on index.html
> +                </p>
- [ ] Kindly decrease the width of this paragraph as per the design template, and just like that perfection is around the corner. 💯️

**Your Design**

![Screenshot from 2023-01-19 17-53-22](https://user-images.githubusercontent.com/17243325/213491488-9fdc837c-f961-4a27-bd97-54696e4331f2.png)

**Figma Design**

![Screenshot from 2023-01-19 17-53-42](https://user-images.githubusercontent.com/17243325/213491591-3e2a05b2-4960-46c4-a7d1-dfe185406d98.png)

2023-01-19 16:04 UTC, amejid commented on index.html
> +                </p>
- [ ] Kindly decrease the width of this paragraph as per the design template, and just like that perfection is around the corner. 💯️

**Your Design**

![Screenshot from 2023-01-19 17-53-22](https://user-images.githubusercontent.com/17243325/213491488-9fdc837c-f961-4a27-bd97-54696e4331f2.png)

**Figma Design**

![Screenshot from 2023-01-19 17-53-42](https://user-images.githubusercontent.com/17243325/213491591-3e2a05b2-4960-46c4-a7d1-dfe185406d98.png)

2023-01-21 06:39 UTC, NahnahAJ requested changes
Hi @ZewdieMc , 

Great work on making the changes requested by a previous reviewer 👏 
You've done very well implementing most of the requested changes, but there are just a few ones that need to be addressed.

<img src="https://media2.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

 ## Highlights
- Good PR title and description :heavy_check_mark: 
- Good commit messages :heavy_check_mark: 
- Very nice design :fire: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 06:39 UTC, NahnahAJ commented on index.html
> +                </p>
- [ ] Great job making all the changes suggested by the previous reviewer :muscle: You only missed this one. 
- [ ] Just like the previous CR mentioned before, I would also suggest that you add a `width: 569px` to this (`p` tag) as shown in the Figma design guidelines below to get the desired look we're aiming for :wink: 
- Figma Design Guide
![image](https://user-images.githubusercontent.com/102699958/213846717-d6401c3a-5249-4db9-ae92-c19f10fae0f9.png)

- [ ] I also noticed that there was an added margin to your `contact me` section and now it looks quite different from the Figma design. I believe this was introduced in your new commit as it didn't look like this the first time you sent it for review so I would suggest you revert back to the old styles for this part or redo it to fit the Figma design :smile: 
- Your Design now
- [ ] You can notice that there is the extra spacing between the blue border and the `Contact me` header.
![image](https://user-images.githubusercontent.com/102699958/213846617-5c1d5d91-de1b-48e5-8c97-c0700beeb890.png)
- The  Figma Design
![image](https://user-images.githubusercontent.com/102699958/213847201-3107effb-a3eb-40e2-bdef-f469518157bf.png)

2023-01-21 12:45 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @ZewdieMc 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-01-21 12:45 UTC, AlphaNtihinduka commented on index.html
> +                <img class="snapshoot desktop" src="./images/Snapshootdsktp1.png" alt="">
- [ ] [OPTIONAL] I have noticed at screen size `768px` and slightly beyond, the `year` goes beyond the width of the card 😞 . Kindly consider increasing the width of the cad to make sure that the year does not cross over.

The design 😎 
![passing](https://user-images.githubusercontent.com/99394374/213867382-12737e52-4d99-45e8-8e4f-60aba7415d44.PNG)

2023-01-22 18:34 UTC, ZewdieMc commented
@NahnahAJ , @amejid , @MILINDI7 , 
I appreciate your feedback. :fire:  It's because of your important and comprehensive comments that this project comes to its next level. Thank you.:pray:
Hope to see you in my next projects. :smiley:

2023-01-22 18:37 UTC, merged